###
# curl -X POST http://localhost:8080/register
#-H "Content-Type: application/json"
#-d '{"username":"testuser","password":"123456"}'
POST http://localhost:8080/user/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "123456"
}
### 订单表，主键id（递增主键），用户id（外键），商品id，数量，价格，订单状态，创建时间，更新时间

POST http://localhost:8080/user/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "123456"
}

POST http://localhost:8080/order/create
Content-Type: application/json

{
    "userId": 1,
    "productId": 101,
    "quantity": 2,
    "price": 49.99,
    "status": "PENDING"
}